# Generated by Django 2.2.4 on 2019-08-08 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190808_1738'),
    ]

    operations = [
    ]
