# Generated by Django 2.2.4 on 2019-08-04 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField(blank=True, null=True)),
                ('restaurant_id', models.IntegerField(blank=True, null=True)),
                ('reser_sum', models.IntegerField(blank=True, null=True)),
                ('resr_status', models.CharField(max_length=1)),
                ('reser_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=20)),
                ('profile_img', models.CharField(blank=True, max_length=250, null=True)),
                ('food_img1', models.CharField(blank=True, max_length=250, null=True)),
                ('food_img2', models.CharField(blank=True, max_length=250, null=True)),
                ('food_img3', models.CharField(blank=True, max_length=250, null=True)),
                ('shop_description', models.TextField(blank=True, null=True)),
                ('food_description', models.TextField(blank=True, null=True)),
                ('shop_location_new', models.CharField(blank=True, max_length=250, null=True)),
                ('shop_location_old', models.CharField(blank=True, max_length=250, null=True)),
                ('shop_comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('givenname', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=1, null=True)),
                ('logined_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user_comments', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
