# Generated by Django 2.2.4 on 2019-08-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=64)),
                ('givenname', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=1)),
                ('logined_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user_comments', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField(blank=True, null=True)),
                ('restaurant_id', models.IntegerField(blank=True, null=True)),
                ('reser_sum', models.IntegerField(blank=True, null=True)),
                ('resr_status', models.CharField(max_length=1)),
                ('reser_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=20)),
                ('profile_img', models.CharField(blank=True, max_length=250, null=True)),
                ('food_img1', models.CharField(blank=True, max_length=250, null=True)),
                ('food_img2', models.CharField(blank=True, max_length=250, null=True)),
                ('food_img3', models.CharField(blank=True, max_length=250, null=True)),
                ('shop_description', models.TextField(blank=True, null=True)),
                ('food_description', models.TextField(blank=True, null=True)),
                ('shop_location', models.CharField(blank=True, max_length=250, null=True)),
                ('shop_comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'restaurant',
                'managed': False,
            },
        ),
    ]
