# Generated by Django 2.2.4 on 2019-08-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='ty',
        ),
    ]
