# Generated by Django 2.2.4 on 2019-08-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_user', '0002_auto_20190808_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ty',
            field=models.IntegerField(null=True),
        ),
    ]
