# Generated by Django 2.2.4 on 2019-08-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_user', '0003_auto_20190808_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ty',
            new_name='userty',
        ),
    ]
