# Generated by Django 2.2.4 on 2019-08-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_user', '0004_auto_20190804_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='member',
        ),
    ]
