# Generated by Django 2.2.4 on 2019-08-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_user', '0004_auto_20190808_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userty',
            new_name='ty',
        ),
    ]
