# Generated by Django 2.2.4 on 2019-08-08 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_user', '0005_auto_20190808_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='resr_status',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reser_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reser_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
